<?php

namespace ContainerN0qP4C1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCommandeDetailRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\CommandeDetailRepository' shared autowired service.
     *
     * @return \App\Repository\CommandeDetailRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\CommandeDetailRepository'] = new \App\Repository\CommandeDetailRepository(($container->services['doctrine'] ?? $container->load('getDoctrineService')));
    }
}
