<?php

namespace ContainerN0qP4C1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCommandeControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\CommandeController' shared autowired service.
     *
     * @return \App\Controller\CommandeController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\CommandeController'] = $instance = new \App\Controller\CommandeController();

        $instance->setContainer(($container->privates['.service_locator.CshazM0'] ?? $container->load('get_ServiceLocator_CshazM0Service'))->withContext('App\\Controller\\CommandeController', $container));

        return $instance;
    }
}
