<?php

namespace Container5yFESEo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArticleRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Repository\ArticleRepository' shared autowired service.
     *
     * @return \App\Repository\ArticleRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Repository'.\DIRECTORY_SEPARATOR.'ArticleRepository.php';

        return $container->privates['App\\Repository\\ArticleRepository'] = new \App\Repository\ArticleRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
