twig:
    default_path: '%kernel.project_dir%/templates'

    form_themes:
        - "bootstrap_5_layout.html.twig"

    globals:
        category_service: '@App\Repository\CategorieRepository'
# permet d'accéder à l'ensemble des propriétés du CategorieRepository dans le layout


when@test:
    twig:
        strict_variables: true
