<?php

namespace ContainerGkHxxDM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DCoJ3xlService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.dCoJ3xl' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.dCoJ3xl'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'repoCommande' => ['privates', 'App\\Repository\\CommandeRepository', 'getCommandeRepositoryService', true],
            'repoDetail' => ['privates', 'App\\Repository\\CommandeDetailRepository', 'getCommandeDetailRepositoryService', true],
            'repoProduit' => ['privates', 'App\\Repository\\ProduitRepository', 'getProduitRepositoryService', true],
            'repoUser' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'repoCommande' => 'App\\Repository\\CommandeRepository',
            'repoDetail' => 'App\\Repository\\CommandeDetailRepository',
            'repoProduit' => 'App\\Repository\\ProduitRepository',
            'repoUser' => 'App\\Repository\\UserRepository',
        ]);
    }
}
