<?php

namespace ContainerGkHxxDM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Xm5anyHService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Xm5anyH' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Xm5anyH'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'requestStack' => ['services', 'request_stack', 'getRequestStackService', false],
            'userRepo' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'requestStack' => '?',
            'userRepo' => 'App\\Repository\\UserRepository',
        ]);
    }
}
