<?php

namespace ContainerGkHxxDM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCommandeDetailRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Repository\CommandeDetailRepository' shared autowired service.
     *
     * @return \App\Repository\CommandeDetailRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Repository'.\DIRECTORY_SEPARATOR.'CommandeDetailRepository.php';

        return $container->privates['App\\Repository\\CommandeDetailRepository'] = new \App\Repository\CommandeDetailRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
