<?php

namespace Container71ZxUur;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_99ZSaa0Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.99ZSaa0' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.99ZSaa0'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'repoComDetail' => ['privates', 'App\\Repository\\CommandeDetailRepository', 'getCommandeDetailRepositoryService', true],
            'repoCommande' => ['privates', 'App\\Repository\\CommandeRepository', 'getCommandeRepositoryService', true],
            'repoProduit' => ['privates', 'App\\Repository\\ProduitRepository', 'getProduitRepositoryService', true],
            'requestStack' => ['services', 'request_stack', 'getRequestStackService', false],
        ], [
            'manager' => '?',
            'repoComDetail' => 'App\\Repository\\CommandeDetailRepository',
            'repoCommande' => 'App\\Repository\\CommandeRepository',
            'repoProduit' => 'App\\Repository\\ProduitRepository',
            'requestStack' => '?',
        ]);
    }
}
