<?php

namespace Container71ZxUur;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_H5w5bWDService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.H5w5bWD' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.H5w5bWD'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'repoProduit' => ['privates', 'App\\Repository\\ProduitRepository', 'getProduitRepositoryService', true],
        ], [
            'repoProduit' => 'App\\Repository\\ProduitRepository',
        ]);
    }
}
