<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerN0qP4C1\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerN0qP4C1/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerN0qP4C1.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerN0qP4C1\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerN0qP4C1\App_KernelProdContainer([
    'container.build_hash' => 'N0qP4C1',
    'container.build_id' => '0c4f0218',
    'container.build_time' => 1683192120,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerN0qP4C1');
