<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container71ZxUur\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container71ZxUur/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container71ZxUur.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container71ZxUur\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container71ZxUur\App_KernelDevDebugContainer([
    'container.build_hash' => '71ZxUur',
    'container.build_id' => '80ed505a',
    'container.build_time' => 1679064675,
], __DIR__.\DIRECTORY_SEPARATOR.'Container71ZxUur');
