<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5yFESEo\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5yFESEo/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container5yFESEo.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container5yFESEo\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container5yFESEo\App_KernelDevDebugContainer([
    'container.build_hash' => '5yFESEo',
    'container.build_id' => 'c3226248',
    'container.build_time' => 1683573604,
], __DIR__.\DIRECTORY_SEPARATOR.'Container5yFESEo');
